'use client';
import { useEffect, useRef } from 'react';
import { Analytics } from '@vercel/analytics/react';
import { VercelSpeedInsights } from '../components/VercelSpeedInsights';
import { Stack, useRouter, usePathname } from 'expo-router';
import { View, ScrollView, Platform } from 'react-native';
import { ensureUser } from '../lib/ensureUser';
import { ensureProfile } from '../lib/ensureProfile';
import { supabase } from '../lib/supabase';
import NavBar from '../components/NavBar';
import Footer from '../components/Footer';
import { CartProvider } from '../context/CartContext';
import { AuthProvider } from '../context/AuthContext';
import { LocationModalProvider } from '../context/LocationModalContext';
import { isInAppBrowser, isAuthOrOnboardingPath } from '../lib/inAppBrowser';
import {
  authErrorToLoginMessage,
  buildAuthCallbackUrl,
  parseSupabaseAuthUrlErrors,
} from '../lib/authUrlErrors';
import { 
  useFonts, 
  OpenSans_300Light,
  OpenSans_400Regular, 
  OpenSans_600SemiBold, 
  OpenSans_700Bold, 
  OpenSans_800ExtraBold 
} from '@expo-google-fonts/open-sans';
import * as SplashScreen from 'expo-splash-screen';

SplashScreen.preventAutoHideAsync();

export default function RootLayout() {
  const router = useRouter();
  const pathname = usePathname();
  const initialized = useRef(false);

  const [fontsLoaded] = useFonts({
    OpenSans_300Light,
    OpenSans_400Regular,
    OpenSans_600SemiBold,
    OpenSans_700Bold,
    OpenSans_800ExtraBold,
  });

  useEffect(() => {
    if (fontsLoaded) {
      SplashScreen.hideAsync();
    }
  }, [fontsLoaded]);

  // Favicon is generated by Expo from app.config web.favicon at build time → /favicon.ico and /favicon.png
  // Cache-busting query forces browsers to fetch the current app logo
  useEffect(() => {
    if (Platform.OS === 'web' && typeof document !== 'undefined') {
      const existingLinks = document.querySelectorAll("link[rel*='icon']");
      existingLinks.forEach(link => link.remove());

      const q = '?v=3';
      const icoLink = document.createElement('link');
      icoLink.rel = 'icon';
      icoLink.href = '/favicon.ico' + q;
      document.head.appendChild(icoLink);

      const pngLink = document.createElement('link');
      pngLink.rel = 'icon';
      pngLink.type = 'image/png';
      pngLink.href = '/favicon.png' + q;
      document.head.appendChild(pngLink);

      const appleLink = document.createElement('link');
      appleLink.rel = 'apple-touch-icon';
      appleLink.href = '/favicon.png' + q;
      document.head.appendChild(appleLink);
    }
  }, []);

  // Supabase may land PKCE codes or errors on Site URL (/) when redirect URL is missing or link expired
  useEffect(() => {
    if (Platform.OS !== 'web' || typeof window === 'undefined') return;

    const href = window.location.href;
    const callbackPath = buildAuthCallbackUrl(href);
    if (callbackPath && !pathname?.startsWith('/auth/callback')) {
      // Full navigation so Supabase can read callback params + stored PKCE verifier reliably.
      window.location.replace(callbackPath);
      return;
    }

    const authError = parseSupabaseAuthUrlErrors(href);
    if (authError && pathname !== '/login') {
      const message = authErrorToLoginMessage(authError);
      window.history.replaceState({}, '', pathname || '/');
      router.replace(`/login?auth_error=${encodeURIComponent(authError.error_code || authError.error)}&auth_message=${encodeURIComponent(message)}` as any);
    }
  }, [pathname, router]);

  // When opened inside Messenger/Facebook/Instagram in-app browser on auth/onboarding pages, send user to /open-in-browser (required for Google sign-in)
  useEffect(() => {
    if (Platform.OS !== 'web') return;
    if (!isInAppBrowser()) return;
    const path = pathname ?? '/';
    if (path === '/open-in-browser') return;
    if (!isAuthOrOnboardingPath(path)) return;
    const then = encodeURIComponent(path);
    router.replace(`/open-in-browser?then=${then}`);
  }, [Platform.OS, pathname, router]);

  // Ensure profile and welcome notification on auth state changes
  useEffect(() => {
    let mounted = true;
    let unsubscribe: (() => void) | null = null;

    async function handleAuthStateChange() {
      try {
        // Check initial session (non-blocking)
        supabase.auth.getSession().then(({ data: sessionData }) => {
          if (sessionData?.session?.user && mounted) {
            // Ensure profile exists (non-blocking - don't wait for welcome notification)
            ensureProfile().catch((err) => {
              console.warn('ensureProfile on initial load error:', err);
            });
          }
        });

        // Subscribe to auth state changes
        const { data: { subscription } } = supabase.auth.onAuthStateChange(async (event, session) => {
          if (mounted && session?.user) {
            // Ensure profile exists (non-blocking - don't wait for welcome notification)
            ensureProfile().catch((err) => {
              console.warn('ensureProfile on auth state change error:', err);
            });
          }
        });

        unsubscribe = subscription?.unsubscribe?.bind(subscription) || null;
      } catch (e: any) {
        console.warn('Error in auth state change handler:', e?.message || e);
      }
    }

    handleAuthStateChange();

    return () => {
      mounted = false;
      if (unsubscribe) {
        try {
          unsubscribe();
        } catch (e) {
          // Ignore unsubscribe errors
        }
      }
    };
  }, []);

  if (!fontsLoaded) {
    return null;
  }

  return (
    <AuthProvider>
      <CartProvider>
        <LocationModalProvider>
          <View style={{ flex: 1, backgroundColor: 'white' }}>
            <Stack screenOptions={{ headerShown: false }} />
            <Analytics />
            <VercelSpeedInsights />
          </View>
        </LocationModalProvider>
      </CartProvider>
    </AuthProvider>
  );
}
