'use client';
import { useEffect, useRef } from 'react';
import { Stack, useRouter, usePathname } from 'expo-router';
import { View, ScrollView, Platform } from 'react-native';
import { ensureUser } from '../lib/ensureUser';
import { ensureProfile } from '../lib/ensureProfile';
import { supabase } from '../lib/supabase';
import NavBar from '../components/NavBar';
import Footer from '../components/Footer';
import { CartProvider } from '../context/CartContext';
import { AuthProvider } from '../context/AuthContext';
import { LocationModalProvider } from '../context/LocationModalContext';
import { redirectAfterLogin } from '../lib/authRedirect';
import { 
  useFonts, 
  OpenSans_300Light,
  OpenSans_400Regular, 
  OpenSans_600SemiBold, 
  OpenSans_700Bold, 
  OpenSans_800ExtraBold 
} from '@expo-google-fonts/open-sans';
import * as SplashScreen from 'expo-splash-screen';

SplashScreen.preventAutoHideAsync();

export default function RootLayout() {
  const router = useRouter();
  const pathname = usePathname();
  const initialized = useRef(false);

  const [fontsLoaded] = useFonts({
    OpenSans_300Light,
    OpenSans_400Regular,
    OpenSans_600SemiBold,
    OpenSans_700Bold,
    OpenSans_800ExtraBold,
  });

  useEffect(() => {
    if (fontsLoaded) {
      SplashScreen.hideAsync();
    }
  }, [fontsLoaded]);

  // Favicon is generated by Expo from app.config web.favicon at build time and served at /favicon.ico
  // We use a cache-busting query param to force browsers to fetch the updated logo
  useEffect(() => {
    if (Platform.OS === 'web' && typeof document !== 'undefined') {
      const existingLinks = document.querySelectorAll("link[rel*='icon']");
      existingLinks.forEach(link => link.remove());

      const iconLink = document.createElement('link');
      iconLink.rel = 'icon';
      iconLink.type = 'image/png';
      iconLink.href = '/favicon.png?v=2'; // v=2 busts cache for logo update
      document.head.appendChild(iconLink);

      const appleLink = document.createElement('link');
      appleLink.rel = 'apple-touch-icon';
      appleLink.href = '/favicon.png?v=2';
      document.head.appendChild(appleLink);
    }
  }, []);

  // Ensure profile and welcome notification on auth state changes
  useEffect(() => {
    let mounted = true;
    let unsubscribe: (() => void) | null = null;

    async function handleAuthStateChange() {
      try {
        // Check initial session (non-blocking)
        supabase.auth.getSession().then(({ data: sessionData }) => {
          if (sessionData?.session?.user && mounted) {
            // Ensure profile exists (non-blocking - don't wait for welcome notification)
            ensureProfile().catch((err) => {
              console.warn('ensureProfile on initial load error:', err);
            });
          }
        });

        // Subscribe to auth state changes
        const { data: { subscription } } = supabase.auth.onAuthStateChange(async (event, session) => {
          if (mounted && session?.user) {
            // Ensure profile exists (non-blocking - don't wait for welcome notification)
            ensureProfile().catch((err) => {
              console.warn('ensureProfile on auth state change error:', err);
            });
          }
        });

        unsubscribe = subscription?.unsubscribe?.bind(subscription) || null;
      } catch (e: any) {
        console.warn('Error in auth state change handler:', e?.message || e);
      }
    }

    handleAuthStateChange();

    return () => {
      mounted = false;
      if (unsubscribe) {
        try {
          unsubscribe();
        } catch (e) {
          // Ignore unsubscribe errors
        }
      }
    };
  }, []);

  if (!fontsLoaded) {
    return null;
  }

  return (
    <AuthProvider>
      <CartProvider>
        <LocationModalProvider>
          <View style={{ flex: 1, backgroundColor: 'white' }}>
            <Stack screenOptions={{ headerShown: false }} />
          </View>
        </LocationModalProvider>
      </CartProvider>
    </AuthProvider>
  );
}
